-- 收银宝分区表
CREATE TABLE IF NOT EXISTS rds_posflow.t1_trxrecprd_v2 (
    p_branch        string,
    sn              string,
    psn             string,
    mcht_cd         string,
    ssfgs           string,
    tzjg            string,
    whjg            string,
    md_id           string,
    term_id         string,
    trans_date      string,
    inst_date       string,
    product_name    string,
    trans_type      string,
    trans_status    string,
    trans_card      string,
    card_type       string,
    card_org        string,
    txn_amt         string,
    trans_amt       string,
    jfzq            string,
    fee_status      string,
    fee             string,
    cost            string,
    service_cost    string,
    income          string,
    MCC18           string,
    MCC42           string,
    zhhqfsbs        string,
    ywlx            string,
    bill_no         string,
    dfsh_no         string,
    dfzh_no         string,
    sstj            string,
    zdsqm           string,
    zdpch           string,
    zdgzh           string,
    jyck_no         string,
    qd_no           string,
    dyqd_mcht_no    string,
    trans_remark    string,
    trans_zy        string,
    trans_ip        string,
    res_code        string,
    commit_time     string,
    error_code      string,
    error_reason    string,
    qdjy_type       string,
    col_01          string,
    col_02          string,
    col_03          string,
    col_04          string,
    col_05          string,
    col_06          string,
    p_end           int
)
PARTITIONED BY (
    p_date date COMMENT '日期分区' -- p_branch STRING COMMENT '分公司分区',
)
STORED AS ORC
-- TBLPROPERTIES ('orc.compress'='SNAPPY')
-- TBLPROPERTIES ('orc.compress'='ZLIB')
-- TBLPROPERTIES ('orc.compress'='NONE')
;